version: 2.1

orbs:
  android: circleci/android@0.2.1

command:
  restore-build-cache:
    description: |
      Restore the Android build cache.
    steps:
      - restore_cache:
          key: android-orb-v1-

  save-build-cache:
    description: |
      Save the Android build cache.
    steps:
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

  store-apk-artifacts:
    description: |
      Save the Android apk
    steps:
      - store_artifacts:
          path: app/build/outputs/apk

jobs:
  build:
    working_directory: ~/ci-assistant
    description: |
      Building CI Assistant

    executor:
      name: android
      sdk-version: "29"

    steps:
      - checkout
      - restore-build-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save-build-cache
      - run:
          command: ./gradlew build
